= Experimental Capabilities

== TODO: Commit Files in Current Repo / New Branch from Main

There may be a need to update files in the repository as part of the workflow, which will continue once the dependent change is approved, applied, and merged.

When there is a need to update a file in the same repo or a different one:

1. Check out the repo in a new directory.
2. Create a branch.
3. Change a file.
4. Commit the change.
5. Create a PR.
6. Save the PR number.

== FAILED: Commit Files in Current Repo / New Branch from the Current One

When a branch is created from another branch, the PR works well; however, after the secondary PR is closed, the preliminary one is closed as well. This is not expected, but it is a consequence of modifying the Terrateam execution context.

== FAILED: Commit Files in Current Repo / Current Branch

The Ansible Terrateam kit comes with a script that commits files changed in the current repository using the Terrateam token available in the environment.

[source,bash]
----
echo "Hello World by Ansible init!" > ${ANSIBLE_ROOT}/hello.txt
export COMMIT_MSG="hello.txt file updated"
${TERRATEAM_ROOT}/.terrateam/shared/commit.sh
----

To be able to write files to the current repository, two configurations must be completed:

1. The GitHub repository must enable workflows to make changes:

`github.com` → `repository` → `Settings` → `Actions` → `General` → `Workflow permissions` → **Read and write permissions**

2. The Terrateam workflow definition must be updated with write permission for the terraform job:

`.github/workflows/terrateam.yml` → `jobs` → `terrateam` → `permissions` → **contents: write**

Problem: Changing a file in the current PR causes the Terrateam engine to run the workflow in the same PR, even for a different directory. Terrateam seems to get confused with workflows, even when assuming it is a layered run.

Solution: Create a new branch out of main, and create a PR for this. Changes should be applied under this new PR.
