---
- name: DuckDuckGo Instant Answer via Ansible (using collection)
  hosts: duck_api
  become: false
  vars_files:
    - vars.json

  roles:
    - role: myorg.publicapi.duckduckgo

  tasks:
    - name: Get Object Storage namespace
      oracle.oci.oci_object_storage_namespace_facts:
      register: ns

    - name: Show namespace
      ansible.builtin.debug:
        msg: "Namespace is {{ ns.namespace }}"
      when: ns.namespace is defined
