---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.json

  tasks:
    - name: Display hello message
      ansible.builtin.debug:
        msg: "Hello World from Ansible! Message: {{ message }}"

    - name: Create a test file
      ansible.builtin.copy:
        content: "This file was created by Ansible"
        dest: "{{ output_file }}"
        mode: "0644"
      when: create_file | default(false)
