
# hooks https://docs.terrateam.io/configuration-reference/hooks
hooks:
  plan:
    pre:
      - type: run
        # scripts must have +x 
        cmd: ['.terrateam/hooks/hello.sh']
        run_on: always
    post:
      - type: run
        cmd: ['.terrateam/hooks/bye.sh']
        run_on: always

dirs:
  terraform:
    tags: [TF_code]
  ansible:
    tags: [ANS_code]
    # layered run
    # https://docs.terrateam.io/advanced-workflows/layered-runs/
    when_modified:
      depends_on: 'dir:terraform'
      "file_patterns": [
          "ansible/vars.json"
          ]
      # autoplan https://docs.terrateam.io/configuration-reference/when-modified
      autoplan: true
        
# workflows https://docs.terrateam.io/configuration-reference/workflows
workflows:
  - tag_query: TF_code
    engine:
      name: terraform
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply

  - tag_query: ANS_code
    engine:
      name: custom
      init: ['../.terrateam/ansible/init.sh']
      # plan: ['bash', '-c', 'scripts/plan.sh', '$TERRATEAM_PLAN_FILE']
      plan: ['bash', '-c', '../.terrateam/ansible/plan.sh $TERRATEAM_PLAN_FILE']
      apply: ['../.terrateam/ansible/apply.sh']
      outputs: ['../.terrateam/ansible/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply