
# cost estimation https://docs.terrateam.io/integrations/cost-estimation/#enabling-cost-estimation
cost_estimation:
  enabled: false

# hooks https://docs.terrateam.io/configuration-reference/hooks
hooks:
  plan:
    pre:
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/hooks/pre_procedure.sh']
        run_on: always
    post:
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/hooks/post_procedure.sh']
        run_on: always

dirs:
  terraform:
    tags: [TF_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
  terraform/ansible:
    tags: [ANS_code]
    when_modified:
      # layered run https://docs.terrateam.io/advanced-workflows/layered-runs/
      depends_on: 'dir:terraform'
      file_patterns: ["${DIR}/*"]
      # autoplan https://docs.terrateam.io/configuration-reference/when-modified
      autoplan: true

  ansible1:
    tags: [code1_ans]
    when_modified:
      file_patterns: ["${DIR}/*"]
      # autoplan https://docs.terrateam.io/configuration-reference/when-modified
      autoplan: true

# workflows https://docs.terrateam.io/configuration-reference/workflows
workflows:
  - tag_query: TF_code
    engine:
      name: terraform
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/terraform/output.sh']

  - tag_query: ANS_code
    engine:
      name: custom
      init:    ['${TERRATEAM_ROOT}/.terrateam/ansible/init.sh']
      plan:    ['${TERRATEAM_ROOT}/.terrateam/ansible/plan.sh', '$TERRATEAM_PLAN_FILE']
      diff:    ['${TERRATEAM_ROOT}/.terrateam/ansible/diff.sh', '$TERRATEAM_PLAN_FILE']
      apply:   ['${TERRATEAM_ROOT}/.terrateam/ansible/apply.sh']
      outputs: ['${TERRATEAM_ROOT}/.terrateam/ansible/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply

  - tag_query: code1_ans
    engine:
      name: custom
      init:    ['${TERRATEAM_ROOT}/.terrateam/ansible/init.sh']
      plan:    ['${TERRATEAM_ROOT}/.terrateam/ansible/plan.sh', '$TERRATEAM_PLAN_FILE']
      diff:    ['${TERRATEAM_ROOT}/.terrateam/ansible/diff.sh', '$TERRATEAM_PLAN_FILE']
      apply:   ['${TERRATEAM_ROOT}/.terrateam/ansible/apply.sh']
      outputs: ['${TERRATEAM_ROOT}/.terrateam/ansible/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply

