
hooks:
  plan:
    pre:
      - type: run
        # scripts must have +x 
        cmd: ['scripts/hello.sh']
        run_on: always
    post:
      - type: run
        cmd: ['scripts/bye.sh']
        run_on: always

dirs:
  test1:
    tags: [test1]
  test2:
    tags: [test2]

workflows:
  - tag_query: test1
    engine:
      name: custom
      init: ['../scripts/init.sh']
      # plan: ['bash', '-c', '../scripts/plan.sh', '$TERRATEAM_PLAN_FILE']
      plan: ['bash', '-c', '../scripts/plan.sh $TERRATEAM_PLAN_FILE']
      apply: ['../scripts/apply.sh']
      outputs: ['../scripts/outputs.sh']
    plan:
      - type: init
      # - type: plan
    apply:
      - type: init
      - type: apply

  - tag_query: test2
    engine:
      name: terraform
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply