
# cost estimation https://docs.terrateam.io/integrations/cost-estimation/#enabling-cost-estimation
cost_estimation:
  enabled: false

# hooks https://docs.terrateam.io/configuration-reference/hooks
hooks:
  plan:
    pre:
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/hooks/pre_procedure.sh']
        run_on: always
      - type: run
        cmd: ['apt-get', 'update']
      - type: run
        cmd: ['apt-get', '-y', 'install', 'python3-yaml']
    post:
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/hooks/post_procedure.sh']
        run_on: always

dirs:
  terraform:
    tags: [TF_code]
    when_modified:
      file_patterns: ["${DIR}/*"]

  terraform/day-1_cfg:
    tags: [ANS_code]
    when_modified:
      depends_on: 'dir:terraform' # layered run https://docs.terrateam.io/advanced-workflows/layered-runs/
      file_patterns: ["${DIR}/*"]
      autoplan: true

  day-2_ops1:
    tags: [ANS_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

  day-2_ops2:
    tags: [ANS_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

  day-2_ops3:
    tags: [ANS_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

  day-2_ops4:
    tags: [ANS_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

  # PROBLEM: workspace1 directories are not triggered at all
  day-2_ops_workspace1: # dir is ok
    workspaces: 
      dev: 
        tags: [DEBUG_code]  # tag is ok
        when_modified:
          file_patterns: ["${DIR}/*"]
          autoplan: true
      prod: 
        tags: [ANS_code]  # tag is ok
        when_modified:
          file_patterns: ["${DIR}/*"]
          autoplan: true

  day-2_ops_workspace2:
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

    workspaces: 
      dev: 
        tags: [DEBUG_code]
      prod: 
        tags: [ANS_code]

  day-2_ops_subdir1/dev: 
    tags: [DEBUG_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

  day-2_ops_subdir1/prod: 
    tags: [ANS_code]
    when_modified:
      file_patterns: ["${DIR}/*"]
      autoplan: true

# workflows https://docs.terrateam.io/configuration-reference/workflows
workflows:
  - tag_query: TF_code
    engine:
      name: terraform
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply
      - type: run
        cmd: ['${TERRATEAM_ROOT}/.terrateam/terraform/output.sh']


  - tag_query: ANS_code
    engine:
      name: custom
      init:    ['${TERRATEAM_ROOT}/.terrateam/ansible/init.sh']
      plan:    ['${TERRATEAM_ROOT}/.terrateam/ansible/plan.sh', '$TERRATEAM_PLAN_FILE']
      diff:    ['${TERRATEAM_ROOT}/.terrateam/ansible/diff.sh', '$TERRATEAM_PLAN_FILE']
      apply:   ['${TERRATEAM_ROOT}/.terrateam/ansible/apply.sh']
      outputs: ['${TERRATEAM_ROOT}/.terrateam/ansible/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply

  - tag_query: DEBUG_code
    engine:
      name: custom
      init:    ['${TERRATEAM_ROOT}/.terrateam/debug/init.sh']
      plan:    ['${TERRATEAM_ROOT}/.terrateam/debug/plan.sh', '$TERRATEAM_PLAN_FILE']
      diff:    ['${TERRATEAM_ROOT}/.terrateam/debug/diff.sh', '$TERRATEAM_PLAN_FILE']
      apply:   ['${TERRATEAM_ROOT}/.terrateam/debug/apply.sh']
      outputs: ['${TERRATEAM_ROOT}/.terrateam/debug/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply
