
hooks:
  plan:
    pre:
      - type: run
        # scripts must have +x 
        cmd: ['scripts/hello.sh']
        run_on: always
    post:
      - type: run
        cmd: ['scripts/bye.sh']
        run_on: always

dirs:
  terraform:
    tags: [TF_code]
  ansible:
    tags: [ANS_code]
    when_modified:
      depends_on: 'dir:terraform'

workflows:
  - tag_query: TF_code
    engine:
      name: terraform
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply

  - tag_query: ANS_code
    engine:
      name: custom
      init: ['../scripts/init.sh']
      # plan: ['bash', '-c', '../scripts/plan.sh', '$TERRATEAM_PLAN_FILE']
      plan: ['bash', '-c', '../scripts/plan.sh $TERRATEAM_PLAN_FILE']
      apply: ['../scripts/apply.sh']
      outputs: ['../scripts/outputs.sh']
    plan:
      - type: init
      - type: plan
    apply:
      - type: init
      - type: apply