---
- name: DuckDuckGo Instant Answer via Ansible (using collection)
  hosts: localhost
  gather_facts: false

  roles:
    - role: myorg.publicapi.duckduckgo

  vars:
    duckduckgo_query: "Jan Matejklo"
