---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.json
  
  tasks:
    - name: Display hello message
      debug:
        msg: "Hello World from Ansible! Message: {{ message }}"
    
    - name: Display environment info
      debug:
        msg: "Environment: {{ environment }}, Version: {{ version }}"
    
    - name: Create a test file
      copy:
        content: "This file was created by Ansible at {{ ansible_date_time.iso8601 }}"
        dest: "{{ output_file }}"
      when: create_file | default(false)
    
    - name: Show summary
      debug:
        msg: |
          Playbook execution completed successfully!
          - Message: {{ message }}
          - Environment: {{ environment }}
          - Version: {{ version }}
          - File created: {{ create_file | default(false) }}
